# initial query for poap subgraph

# NOTE: There are better ways to query graphql with python. This is a test file to store example queries.
# See The Graph explorer: https://thegraph.com/explorer/subgraph/poap-xyz/poap-xdai
# See xDai Chain explorer on blockscout: https://blockscout.com/xdai/mainnet/tokens/0x22c1f6050e56d2876009903609a2cc3fef83b415/instance/317221/token-transfers

# POAP GraphQL Schema:
# Token
# Account
# Event
# Transfer
# _Meta_     (access to subgraph metadata)

{
  tokens(first: 5) {
    id
    owner {
      id
    }
    event {
      id
    }
    transfers {
      id
    }
  }
  accounts(first: 5) {
    id
    tokens {
      id
    }
    tokensOwned
  }
  events(where: { id: 2655 }) {
    # Event id: 2655, Bankless DAO Community Call #4, source: https://poap.gallery/event/2655
    id
    tokens {
      id
      owner {
        id
      }
      transfers {
        id
        from {
          id
        }
        to {
          id
        }
      }
    }
  }
  _meta {
    hasIndexingErrors
  }
}
